### ISSUE TITLE
duckdb, sequence function inside F.expr resolves to sequence function instead of generate_series

### ISSUE THREAD

**Issue by cristian-marisescu** [eakmanrq/sqlframe#111]
Hi,

I'm using the following code to create a sequence between start - end date, but within an `expr()` instead of `F.sequence`.
While the `F.sequence` correctly resolves to duckdb `generate_series`, `F.expr("sequence")` won't
```python
import sqlframe.duckdb.functions as F
from sqlframe.duckdb import DuckDBSession

session = DuckDBSession()


df = session.createDataFrame(
    [("2024-01-01", "2024-05-05"), ("2024-05-21", "2024-12-05")],
    ["start_date", "end_date"],
).select(
    F.col("start_date").cast("date").alias("start_date"),
    F.col("end_date").cast("date").alias("end_date"),
)

df = df.withColumn(
    "date_sequence",
    F.expr(
        "sequence(start_date,end_date, interval 1 month)",
    ),
)

print(df.sql())
print(df.show())
```

will return

```bash
SELECT
  CAST(CAST("a1"."start_date" AS TEXT) AS DATE) AS "start_date",
  CAST(CAST("a1"."end_date" AS TEXT) AS DATE) AS "end_date",
  SEQUENCE(
    CAST(CAST("a1"."start_date" AS TEXT) AS DATE),
    CAST(CAST("a1"."end_date" AS TEXT) AS DATE),
    INTERVAL '1' MONTH
  ) AS "date_sequence"
FROM (VALUES
  ('2024-01-01', '2024-05-05'),
  ('2024-05-21', '2024-12-05')) AS "a1"("start_date", "end_date")
Traceback (most recent call last):
  File "/workspaces/playground.py", line 29, in <module>
    print(df.show())
  File "/workspaces/.venv/lib/python3.10/site-packages/sqlframe/base/dataframe.py", line 1576, in show
    result = self.session._fetch_rows(sql)
  File "/workspaces/.venv/lib/python3.10/site-packages/sqlframe/base/session.py", line 458, in _fetch_rows
    self._execute(sql, quote_identifiers=quote_identifiers)
  File "/workspaces/.venv/lib/python3.10/site-packages/sqlframe/base/session.py", line 430, in _execute
    self._cur.execute(self._to_sql(sql, quote_identifiers=quote_identifiers))
duckdb.duckdb.CatalogException: Catalog Error: Scalar Function with name sequence does not exist!
Did you mean "encode"?
LINE 1: ...37156 AS (SELECT start_date, end_date, SEQUENCE(start_date, end_date, INTERVAL...
```

**Comment by eakmanrq** [comment]
The core of the issue is that SQLGlot doesn't understand that Spark's `sequence` maps to `GenerateSeries`:

```
>>> parse_one("SELECT sequence(start, end, interval 1 month)", dialect="spark").sql(dialect="duckdb")
"SELECT SEQUENCE(start, end, INTERVAL '1' MONTH)"
```

It should map to this: https://github.com/tobymao/sqlglot/blob/a8ce90ca8a8d78ffb4c87660a918fb6025de1800/sqlglot/expressions.py#L4813

If you would like to see that fixed then you would need to open an issue in SQLGlot. 

In general, SQLFrame will have deeper understanding of converting PySpark's functions to other engines because I create overrides just within SQLFrame. Eventually I intend to get these applied SQLGlot, so SQL parsing would also have the conversion, but it would significantly slow down development so I'm waiting to do this later.
