### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by eredzik** [eakmanrq/sqlframe#184]
```py
from sqlframe.standalone import functions as SF

employee = get_df("employee")
store = get_df("store")
district = get_df("district")
result = (
        employee
        .alias('employee')
        .join(
            store
            .filter(SF.col("store_name") != "test") 
            .alias('store'),
            on=SF.col('employee.employee_id') == SF.col('store.store_id')
        )
        .select('employee.*', 'store.*') # When there is such select it throws error
        .join( # Exception raised here
            district
            .alias('district'),
            on=SF.col('store.store_id') == SF.col('district.district_id')
        )
        
    )
result.show()
```

Throws error: 
```
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/home/emil/projects/sqlframe/sqlframe/base/dataframe.py", line 1580, in show
    result = df.limit(n).collect()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/dataframe.py", line 1550, in collect
    return self._collect()
           ^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/dataframe.py", line 1553, in _collect
    return self.session._collect(self._get_expressions(optimize=False), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/session.py", line 493, in _collect
    self._execute(sql)
  File "/home/emil/projects/sqlframe/sqlframe/duckdb/session.py", line 72, in _execute
    self._last_result = self._cur.execute(sql)  # type: ignore
                        ^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.BinderException: Binder Error: Referenced table "t15874714" not found!
Candidate tables: "t11089442", "t41607634"
LINE 1: ... "t41607634" INNER JOIN "t11089442" ON "t15874714"."store_id" = "t11089442"."d...
```

There is also separate issue when instead of `.select('employee.*', 'store.*')` I use `.select(F.col('employee.*'), F.col('store.*')`:

```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/home/emil/projects/sqlframe/sqlframe/base/operations.py", line 48, in wrapper
    df: t.Union[_BaseDataFrame, _BaseGroupedData] = func(self, *args, **kwargs)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/dataframe.py", line 705, in select
    columns = self._ensure_and_normalize_cols(cols)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/dataframe.py", line 365, in _ensure_and_normalize_cols
    cols = self._ensure_list_of_columns(cols)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/dataframe.py", line 358, in _ensure_list_of_columns
    return Column.ensure_cols(ensure_list(cols))  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/column.py", line 138, in ensure_cols
    return [cls.ensure_col(x) if not isinstance(x, Column) else x for x in args]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/column.py", line 138, in <listcomp>
    return [cls.ensure_col(x) if not isinstance(x, Column) else x for x in args]
            ^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/column.py", line 134, in ensure_col
    return col(value)
           ^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/functions.py", line 41, in col
    return Column(column_name)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/column.py", line 31, in __init__
    expression = self._lit(expression).expression  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/sqlframe/base/column.py", line 176, in _lit
    return cls(exp.convert(value))
               ^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7685, in convert
    expressions=[
                ^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7686, in <listcomp>
    PropertyEQ(this=to_identifier(k), expression=convert(v, copy=copy))
                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7685, in convert
    expressions=[
                ^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7686, in <listcomp>
    PropertyEQ(this=to_identifier(k), expression=convert(v, copy=copy))
                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7685, in convert
    expressions=[
                ^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7686, in <listcomp>
    PropertyEQ(this=to_identifier(k), expression=convert(v, copy=copy))
                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7685, in convert
    expressions=[
                ^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7686, in <listcomp>
    PropertyEQ(this=to_identifier(k), expression=convert(v, copy=copy))
                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7685, in convert
    expressions=[
                ^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7686, in <listcomp>
    PropertyEQ(this=to_identifier(k), expression=convert(v, copy=copy))
                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/projects/sqlframe/.venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 7690, in convert
    raise ValueError(f"Cannot convert {value}")
ValueError: Cannot convert <unlocked _thread.RLock object owner=0 count=0 at 0x7353bf1b5980>
```

**Comment by eakmanrq** [comment]
What is interesting is your workaround with the alias is still not correct. That is because there are duplicate store_ids and in duckdb it is picking the first one. So Spark is automatically dealing with the ambiguity here. It seems like in the first example the "store_id" column from "store" is used instead of employee. This seems to break a general rule that exists which is that columns are resolve left -> right which is likely because the column was used in the join. 

This is a bit trickier to solve since I need to better understand how Spark's handles this kind of ambiguity in order to properly replicate it. Thanks for pointing this out!
