### ISSUE TITLE
`df.filter(F.col('a').alias('a'))` raises

### ISSUE THREAD

**Issue by MarcoGorelli** [eakmanrq/sqlframe#232]
```python
session = sqlframe.duckdb.DuckDBSession()
import sqlframe.duckdb.functions as F
df = session.createDataFrame([{'a': 1, 'b': 2}, {'a': 2, 'b': 3}])
df.filter((F.col('a')>1).alias('a')).show()
```
```
Traceback (most recent call last):
  File "/home/marcogorelli/polars-api-compat-dev/t.py", line 14, in <module>
    df.filter((F.col('a')>1).alias('a')).show()
  File "/home/marcogorelli/polars-api-compat-dev/.venv/lib/python3.12/site-packages/sqlframe/base/dataframe.py", line 1629, in show
    result = df.limit(n).collect()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/.venv/lib/python3.12/site-packages/sqlframe/base/dataframe.py", line 1599, in collect
    return self._collect()
           ^^^^^^^^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/.venv/lib/python3.12/site-packages/sqlframe/base/dataframe.py", line 1602, in _collect
    return self.session._collect(self._get_expressions(optimize=False), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/.venv/lib/python3.12/site-packages/sqlframe/base/session.py", line 493, in _collect
    self._execute(sql)
  File "/home/marcogorelli/polars-api-compat-dev/.venv/lib/python3.12/site-packages/sqlframe/duckdb/session.py", line 72, in _execute
    self._last_result = self._cur.execute(sql)  # type: ignore
                        ^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "AS"
```

**Comment by eakmanrq** [comment]
Confirmed this is valid PySpark, but what is the purpose of `alias` in this example? You are aliasing a filter condition but it doesn't change the output in any way nor do I see how it could be useful in constructing a Dataframe.

**Comment by MarcoGorelli** [comment]
thanks - there's no purpose, it's just something we do internally in some cases to preserve the column name
